export * from "./generated/api";
export type {
  HealthStatus,
  ErrorResponse,
  RegisterRequest,
  LoginRequest,
  AuthResponse,
  User,
  Barber,
  UpdateBarberRequest,
  Availability,
  AvailabilityInput,
  AppointmentSlot,
  CreateSlotRequest,
  UpdateSlotRequest,
  AppointmentStatus,
  Appointment,
  CreateAppointmentRequest,
  UpdateAppointmentRequest,
  NoShowBlock,
  CreateBlockRequest,
  Message,
  SendMessageRequest,
  BarberDashboard,
  ListAppointmentsParams,
  GetBarberDashboardParams,
  RegisterRequestRole,
  UserRole,
} from "./generated/types";
