// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tiras-tema/AnthraciteGold.tsx": () => import("../components/mockups/tiras-tema/AnthraciteGold.tsx"),
  "./components/mockups/tiras-tema/EmeraldCopper.tsx": () => import("../components/mockups/tiras-tema/EmeraldCopper.tsx"),
  "./components/mockups/tiras-tema/NavyGold.tsx": () => import("../components/mockups/tiras-tema/NavyGold.tsx")
};
