import {
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { usersTable } from "./users";

export const passwordResetChannelEnum = pgEnum("password_reset_channel", [
  "email",
  "phone",
]);

export const passwordResetsTable = pgTable(
  "password_resets",
  {
    // Generated by the API so a decoy ID can have the same shape.
    id: text("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => usersTable.id, { onDelete: "cascade" }),
    channel: passwordResetChannelEnum("channel").notNull(),
    codeHash: text("code_hash").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    attemptCount: integer("attempt_count").notNull().default(0),
    verifiedAt: timestamp("verified_at"),
    resetTokenHash: text("reset_token_hash").unique(),
    tokenExpiresAt: timestamp("token_expires_at"),
    usedAt: timestamp("used_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => ({
    userCreatedAtIndex: index("password_resets_user_created_at_idx").on(
      table.userId,
      table.createdAt,
    ),
  }),
);

export const insertPasswordResetSchema = createInsertSchema(
  passwordResetsTable,
).omit({
  attemptCount: true,
  verifiedAt: true,
  resetTokenHash: true,
  tokenExpiresAt: true,
  usedAt: true,
  createdAt: true,
});

export type InsertPasswordReset = z.infer<typeof insertPasswordResetSchema>;
export type PasswordReset = typeof passwordResetsTable.$inferSelect;
